import getOrderModels from "../models/Order";
import getMessageModel from "../models/Message"
import getConversationModel from "../models/Conversation"

class ChatService {
    /**
     * Initialize driver-client conversation when order is accepted
     * Creates DRIVER_CLIENT conversation with welcome message
     */
    static async initializeDriverClientConversation({
                                                        orderId,
                                                        driverId,
                                                        driverName,
                                                        clientId,
                                                        orderRef,
                                                        vehicleType,
                                                        estimatedETA
                                                    }) {
        try {
            const Conversation = await getConversationModel();
            const Message = await getMessageModel();

            // Check if conversation already exists for this order
            const existingConversation = await Conversation.findOne({
                type: 'DRIVER_CLIENT',
                orderId: orderId,
                status: 'open'
            });

            if (existingConversation) {
                console.log(`✅ Conversation already exists for order: ${orderRef}`);
                return {
                    success: true,
                    conversation: existingConversation,
                    isNew: false
                };
            }

            // Create new conversation
            const conversation = await Conversation.create({
                type: 'DRIVER_CLIENT',
                orderId: orderId,
                participants: [
                    { userId: driverId, role: 'Driver', lastReadSeq: 0 },
                    { userId: clientId, role: 'Client', lastReadSeq: 0 }
                ],
                status: 'open',
                deleteControl: "ADMIN_ONLY",
                createdBy: driverId,
                lastActivityBy: driverId,
                metadata: {
                    orderRef,
                    vehicleType,
                    estimatedETA,
                    initiatedAt: new Date()
                }
            });

            // Create welcome message from driver
            const welcomeText = `Hi! I'm ${driverName}, and I've accepted your order ${orderRef}. I'm on my way to the pickup location. Feel free to reach out if you have any questions! 🚚`;

            const welcomeMessage = await Message.create({
                conversationId: conversation._id,
                seq: 1,
                senderId: driverId,
                senderRole: 'Driver',
                kind: 'text',
                body: welcomeText,
                createdAt: new Date(),
                metadata: {
                    isAutoGenerated: true,
                    orderRef,
                    eventType: 'order_accepted'
                }
            });

            // Update conversation with first message
            await Conversation.updateOne(
                { _id: conversation._id },
                {
                    $inc: { nextSeq: 1, messageCount: 1 },
                    $set: { lastMessageAt: new Date() }
                }
            );

            console.log(`✅ Created driver-client conversation for order: ${orderRef}`);

            // Emit real-time notification to client
            if (global.io) {
                const clientRoom = `user:${clientId}`;

                // Notify client about new conversation
                global.io.to(clientRoom).emit('chat:conversation:new', {
                    conversationId: conversation._id,
                    type: 'DRIVER_CLIENT',
                    orderRef,
                    driverName,
                    message: welcomeMessage.toObject()
                });

                // Also emit the message itself
                global.io.to(clientRoom).emit('chat:message:new', welcomeMessage.toObject());

                console.log(`📡 Notified client ${clientId} about new conversation`);
            }

            return {
                success: true,
                conversation: conversation.toObject(),
                welcomeMessage: welcomeMessage.toObject(),
                isNew: true
            };

        } catch (error) {
            console.error('❌ Error initializing driver-client conversation:', error);
            return {
                success: false,
                error: error.message
            };
        }
    }

    /**
     * Send system message to conversation
     * Useful for order status updates in chat
     */
    static async sendSystemMessage({
                                       conversationId,
                                       message,
                                       metadata = {}
                                   }) {
        try {
            const Conversation = await getConversationModel();
            const Message = await getMessageModel();

            // Update conversation and get updated document
            const conversation = await Conversation.findOneAndUpdate(
                { _id: conversationId },
                {
                    $inc: { nextSeq: 1, messageCount: 1 },
                    $set: { lastMessageAt: new Date() }
                },
                { new: true }
            );

            if (!conversation) {
                return { success: false, error: 'Conversation not found' };
            }

            // Create system message
            const systemMessage = await Message.create({
                conversationId,
                seq: conversation.nextSeq - 1,
                senderId: null,
                senderRole: 'System',
                kind: 'system',
                body: message,
                createdAt: new Date(),
                metadata
            });

            // Emit to all participants
            if (global.io) {
                global.io.to(conversationId.toString()).emit('chat:message:new', systemMessage.toObject());

                // Also emit to personal rooms
                conversation.participants.forEach(participant => {
                    const personalRoom = `user:${participant.userId}`;
                    global.io.to(personalRoom).emit('chat:message:new', systemMessage.toObject());
                });
            }

            return {
                success: true,
                message: systemMessage.toObject()
            };

        } catch (error) {
            console.error('❌ Error sending system message:', error);
            return { success: false, error: error.message };
        }
    }

    /**
     * Close conversation when order is completed
     */
    static async closeConversation(conversationId, reason = 'order_completed') {
        try {
            const Conversation = await getConversationModel();

            const conversation = await Conversation.findByIdAndUpdate(
                conversationId,
                {
                    $set: {
                        status: 'closed',
                        closedAt: new Date(),
                        closeReason: reason
                    }
                },
                { new: true }
            );

            if (!conversation) {
                return { success: false, error: 'Conversation not found' };
            }

            // Send closing system message
            await this.sendSystemMessage({
                conversationId,
                message: 'This conversation has been closed as the order is now complete. Thank you! 🎉',
                metadata: {
                    eventType: reason,
                    closedAt: new Date()
                }
            });

            console.log(`✅ Closed conversation: ${conversationId}`);

            return {
                success: true,
                conversation: conversation.toObject()
            };

        } catch (error) {
            console.error('❌ Error closing conversation:', error);
            return { success: false, error: error.message };
        }
    }

    /**
     * Get or create any type of conversation
     * Used for ensuring conversations exist before sending messages
     */
    static async getOrCreateConversation({ type, participants, orderId = null, metadata = {} }) {
        try {
            const Conversation = await getConversationModel();

            // Try to find existing conversation
            const query = {
                type,
                status: 'open',
                'participants.userId': { $all: participants.map(p => p.userId) }
            };

            if (orderId) {
                query.orderId = orderId;
            }

            let conversation = await Conversation.findOne(query);

            if (conversation) {
                return {
                    success: true,
                    conversation: conversation.toObject(),
                    isNew: false
                };
            }

            // Create new conversation
            conversation = await Conversation.create({
                type,
                orderId,
                participants,
                status: 'open',
                deleteControl: type === 'DRIVER_CLIENT' ? 'NONE' : 'ADMIN_ONLY',
                createdBy: participants[0].userId,
                lastActivityBy: participants[0].userId,
                metadata
            });

            return {
                success: true,
                conversation: conversation.toObject(),
                isNew: true
            };

        } catch (error) {
            console.error('❌ Error getting/creating conversation:', error);
            return { success: false, error: error.message };
        }
    }
}

module.exports = ChatService;